package: urlaub
version: '1.0.0-dev-2025-02-10'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/urlaub

requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.16
    packages:
        yrewrite: "^4"

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
