package: urlaub
version: '0.0.1-dev'
author: 'Alexander Walther'
supportpage: 'https://github.com/alexplusde/urlaub'

page:
    title: 'translate:urlaub_title'
    perm: urlaub[]
    icon: rex-icon fa-link
    subpages:
        profiles:
            title: 'translate:urlaub_profiles'
            perm: urlaub[profiles]
        urls:
            title: 'translate:urlaub_urls'
            perm: urlaub[urls]
        settings:
            title: 'translate:urlaub_settings'
            perm: urlaub[settings]

requires:
    redaxo: '^5.19.0'
    packages:
        yform: '^5.0'
        yrewrite: '^2.10'

conflicts:
    packages:
#        url: '*'
